---
# Role: SELinux Hardening

- name: Ensure SELinux package is installed
  yum:
    name: selinux-policy-targeted
    state: present
  tags: selinux

- name: Ensure SELinux config file exists
  file:
    path: /etc/selinux/config
    state: touch
  tags: selinux

- name: Set SELinux to enforcing
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    backup: yes
  tags: selinux

- name: Set SELinux type to targeted
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUXTYPE='
    line: 'SELINUXTYPE=targeted'
    backup: yes
  tags: selinux

- name: Enforce SELinux immediately
  command: setenforce 1
  tags: selinux

- name: Ensure reports directory exists
  file:
    path: "/home/{{ lookup('env','USER') }}/reports/selinux"
    state: directory
    mode: '0755'
  tags: selinux

- name: Save current SELinux status
  command: getenforce
  register: selinux_status
  changed_when: false
  tags: selinux

- name: Save SELinux report
  copy:
    content: "{{ selinux_status.stdout }}"
    dest: "/home/{{ lookup('env','USER') }}/reports/selinux/selinux-status.txt"
    mode: '0644'
  tags: selinux
