---
# Role: TLS - Self-Signed Certificate Generation

- name: Ensure OpenSSL is installed
  yum:
    name: openssl
    state: present
  tags: tls

- name: Ensure TLS reports directory exists
  file:
    path: "/home/{{ lookup('env','USER') }}/reports/tls"
    state: directory
    mode: '0755'
  tags: tls

# Option 1: create /etc/ssl/private for traditional location (optional)
- name: Ensure /etc/ssl/private directory exists
  file:
    path: /etc/ssl/private
    state: directory
    mode: '0700'
  tags: tls

- name: Generate self-signed certificate (if not exists)
  command: >
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509
    -subj "/C=PK/ST=Sindh/L=Karachi/O=Portfolio/CN=localhost"
    -keyout "/home/{{ lookup('env','USER') }}/reports/tls/selfsigned.key"
    -out "/home/{{ lookup('env','USER') }}/reports/tls/selfsigned.crt"
  args:
    creates: "/home/{{ lookup('env','USER') }}/reports/tls/selfsigned.crt"
  tags: tls
