---
# Role: Auditd - System Logging & Auditing

- name: Install auditd package
  yum:
    name: audit
    state: present
  tags: auditd

- name: Ensure auditd service is enabled and started
  service:
    name: auditd
    state: started
    enabled: yes
  tags: auditd

- name: Apply basic audit rules
  copy:
    dest: /etc/audit/rules.d/audit.rules
    content: |
      # Log all changes to /etc/passwd
      -w /etc/passwd -p wa -k passwd_changes
      # Log all changes to /etc/shadow
      -w /etc/shadow -p wa -k shadow_changes
      # Log executions of sudo commands
      -w /usr/bin/sudo -p x -k sudo_commands
  notify: restart auditd
  tags: auditd

- name: Ensure reports directory exists
  file:
    path: "/home/{{ lookup('env','USER') }}/reports/auditd"
    state: directory
    mode: '0755'
  tags: auditd

- name: Save current audit rules
  command: auditctl -l
  register: auditd_rules
  changed_when: false
  tags: auditd

- name: Save audit rules report
  copy:
    content: "{{ auditd_rules.stdout }}"
    dest: "/home/{{ lookup('env','USER') }}/reports/auditd/auditd-rules.txt"
    mode: '0644'
  tags: auditd

# Handlers
- name: restart auditd
  service:
    name: auditd
    state: restarted
  tags: auditd
