---
# Role: AIDE - Intrusion Detection

- name: Install AIDE package
  yum:
    name: aide
    state: present

- name: Initialize AIDE database
  command: aide --init
  args:
    creates: /var/lib/aide/aide.db.new.gz

- name: Move new AIDE database into place
  command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    removes: /var/lib/aide/aide.db.new.gz

- name: Run AIDE check
  command: aide --check
  register: aide_check
  changed_when: false

- name: Save AIDE report
  copy:
    content: "{{ aide_check.stdout }}"
    dest: "/home/{{ lookup('env','USER') }}/reports/aide/aide-report.txt"
    mode: '0644'
