---
# Role: OpenSCAP Compliance Scanning and Remediation with Before/After Reports

- name: Install OpenSCAP packages
  yum:
    name:
      - openscap-scanner
      - scap-security-guide
    state: present

- name: Ensure reports directory exists
  file:
    path: "/home/{{ lookup('env','USER') }}/reports/openscap/before"
    mode: '0755'
    state: directory

- name: Run OpenSCAP CIS scan (Before Remediation)
  command: >
    oscap xccdf eval
    --profile xccdf_org.ssgproject.content_profile_cis
    --results /home/{{ lookup('env','USER') }}/reports/openscap/before/cis-results.xml
    --report /home/{{ lookup('env','USER') }}/reports/openscap/before/cis-report.html
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
  args:
    creates: /home/{{ lookup('env','USER') }}/reports/openscap/before/cis-report.html

- name: Generate CIS remediation script
  command: >
    oscap xccdf generate fix
    --profile xccdf_org.ssgproject.content_profile_cis
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
    > /home/{{ lookup('env','USER') }}/reports/openscap/cis-remediate.sh
  args:
    creates: /home/{{ lookup('env','USER') }}/reports/openscap/cis-remediate.sh

- name: Backup critical system files before remediation
  copy:
    src: "{{ item }}"
    dest: "/home/{{ lookup('env','USER') }}/reports/openscap/backups/{{ item | basename }}"
    mode: '0644'
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth
    - /etc/pam.d/fingerprint-auth
    - /etc/pam.d/smartcard-auth
    - /etc/pam.d/postlogin
    - /etc/nsswitch.conf

- name: Apply CIS remediation script
  command: "bash /home/{{ lookup('env','USER') }}/reports/openscap/cis-remediate.sh --force"
  ignore_errors: yes

- name: Ensure after reports directory exists
  file:
    path: "/home/{{ lookup('env','USER') }}/reports/openscap/after"
    mode: '0755'
    state: directory

- name: Run OpenSCAP CIS scan (After Remediation)
  command: >
    oscap xccdf eval
    --profile xccdf_org.ssgproject.content_profile_cis
    --results /home/{{ lookup('env','USER') }}/reports/openscap/after/cis-results.xml
    --report /home/{{ lookup('env','USER') }}/reports/openscap/after/cis-report.html
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
  args:
    creates: /home/{{ lookup('env','USER') }}/reports/openscap/after/cis-report.html
